apiVersion: v1
kind: Pod
metadata:
  name: posenet-demo
spec:
  containers:
  - name: posenet-demo-simplepose
    image: yjungku/posenet-demo ### not sure ###
    ports:
    - containerPort: 80
  nodeSelector:
    k3s.io/tpu: true
