apiVersion: v1
kind: Pod
metadata:
  name: posenet-demo
spec:
  containers:
  - name: posenet-demo-simplepose
    image: doijanky/hello-world
    ports:
    - containerPort: 80
  nodeSelector:
    k3s.io/tpu: "true"
