apiVersion: v1
kind: Pod
metadata:
  name: helloworld-demo
spec:
  containers:
  - name: helloworld-demo
    image: helloworld
    ports:
    - containerPort: 80
  nodeSelector:
    k3s.io/tpu: "true"
